name: party_games
description: Drinking party games.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tasks.yaml
    - assets/topics.yaml
    - assets/words.yaml
